### ISSUE TITLE
Admin Interface is invisible per default

### ISSUE THREAD

**Issue by 1letter** [plone/plone.distribution#100]
## What i did:
- `docker run -p 8080:8080 plone/plone-backend:6.1.0b1`
- Got to: `http://localhost:8080`

## What i get:

an empty Page, see screenshot

## What i want:

a visible admin interface

![Screenshot from 2024-11-07 07-29-36](https://github.com/user-attachments/assets/249c17cb-2c1f-48f6-9b25-e6d5ba79eb71)

The style rule is wrong 
```
.container.admin {
    opacity: 0;
    transition: opacity .8s ease-in-out;
}
```

**Comment by stevepiercy** [comment]
@1letter did https://github.com/plone/plone.distribution/pull/102 fix this issue?
