### ISSUE TITLE
React App sometimes fails to load 

### ISSUE THREAD

**Issue by JeffersonBledsoe** [plone/plone.distribution#94]
Mostly happens on Safari, but noticed on Chrome and Firefox too. Not sure yet what the cause is. Leaves the page empty so we can't do anything

**Comment by stevepiercy** [comment]
@JeffersonBledsoe please provide the steps to reproduce the issue and a stack trace or anything useful from the browser's developer tools to diagnose what is going on.

**Comment by JeffersonBledsoe** [comment]
Thanks for the quick response. There wasn't any browser logs, nor were there any noticeable steps to reproduce beyond trying to load the distributions main page and it just being blank. I noticed that the "on load" wasn't being triggered so my assumption is the app isn't loading correctly. I've yet to investigate further, just wanted to log this before it got forgotten

**Comment by JeffersonBledsoe** [comment]
Solved by https://github.com/plone/plone.distribution/pull/102
